### ISSUE TITLE
Error while highlighting switch case

### ISSUE THREAD

**Issue by hollesse** [LucaVazz/SetlXHelper#7]
Deleted it because it was stupid!

**Comment by hollesse** [comment]
Sorry I am stupid! It's my fault!

**Comment by hollesse** [comment]
But i've got something new :) the default: does not get highlighted... 
<img width="443" alt="bildschirmfoto 2018-02-27 um 14 17 52" src="https://user-images.githubusercontent.com/15342769/36730827-072f1afe-1bc9-11e8-846e-9aa5cfd9fa19.png">

**Comment by LucaVazz** [comment]
fixed in version 1.3.1
